name: Actions Runner Controller Demo
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: self-hosted
    steps:
    - run: echo "🎉 This job uses runner scale set runners!"
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.2'
        bundler: '2.4.12'
        bundler-cache: true
    - run: gem install --version 0.12.1 uri
    - run: ruby --version
